version: 2

references:
  jvm_cache_keys: &jvm_cache_keys
    - v1-jvm-deps-{{ checksum "server/build.gradle" }}-{{ checksum "server/gradle.properties" }}
    - v1-jvm-deps-{{ checksum "server/build.gradle" }}-
    - v1-jvm-deps-
  nvm-cache-keys: &npm_cache_keys
    - v1-nvm-deps-{{ checksum "package.json" }}
    - v1-nvm-deps-

  jvm_cache_key: &jvm_cache_key
    v1-jvm-deps-{{ checksum "server/build.gradle" }}-{{ checksum "server/gradle.properties" }}

  npm_cache_key: &npm_cache_key
    v1-nvm-deps-{{ checksum "package.json" }}

jobs:
  build:
    working_directory: /home/work/build
    docker:
      - image: msimmons/nodejvm:latest
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - restore_cache:
          keys:
            *jvm_cache_keys
      - restore_cache:
          keys:
            *npm_cache_keys
      - run: 
          shell: /bin/bash --login -eo pipefail 
          command: |
            source ~/.nvm/nvm.sh
            nvm i 8
            npm i vsce -g
            npm install
            vsce package

      - save_cache:
          key: *jvm_cache_key
          paths:
            - ~/.m2
            - ~/.gradle
      - save_cache:
          key: *npm_cache_key
          paths:
            - node_modules
            - ~/.nvm
      - store_artifacts:
          path: jvmcode*.vsix
      - store_test_results:
          path: server/build/test-results
workflows:
  version: 2
  build_publish:
    jobs:
      - build